### ISSUE TITLE
Nexus OSS service not running.

### ISSUE THREAD

**Issue by sernapallyanurag** [jsirex/simple-nexus-cookbook#1]
After installation of nexus, when I do 

`service nexus status`

`Nexus OSS is not running.`

I get this output.
I tried restarting. It starts for a moment and then stops.
I am unable to access using web browser.

**Comment by jsirex** [comment]
Do you have any additional logs?
Have you installed compatible java runtime?

**Comment by sernapallyanurag** [comment]
Yes I have Installed OpenJDK using Java cookbook's default recipe. I have no additional logs as chef client run is successful. I can provide You with `netstat  -tnlp` which doesnot show any service running on `port-8081`

`
PID/Program name
tcp        0      0 xx.xx.xx.xx:16001     0.0.0.0:*               LISTEN
897/python
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
1608/sshd
tcp6       0      0 :::22                   :::*                    LISTEN
1608/sshd
`

**Comment by sernapallyanurag** [comment]
The problem has been resolved. My java recipe was installing `Open-JDK 6` due to which the server was not getting started.
I am using Oracle flavor of JAVA version 8.
Thank you for the response. I am closing this issue.
